name: Publish PowerShell
description: |
  Publish a PowerShell module or script to GitHub Packages, the Posh Test
  Gallery, or the PowerShell Gallery.
inputs:
  token:
    description: |
      Token to authenticate.
    required: true
  target:
    description: |
      Set to `packages` for GitHub Packages, `testgallery` for Posh Test 
      Gallery, or `gallery` for PowerShell Gallery.
    required: true
  path:
    description: |
      Path to publish relative to the root of the project. For a module, 
      should be the path to the .psm1 file. For a script, should be the 
      path to the .ps1 file.
runs:
  using: "composite"
  steps:
    - name: Publish to Packages
      run: |
        Install-Module PowerShellGet -AllowPrerelease -Force -Repository PSGallery -SkipPublisherCheck

        $FullPath = "${{ github.workspace }}\${{ inputs.path }}"

        $NuGetUri = "https://nuget.pkg.github.com/${{ github.repository_owner }}"

        $LocalRepoPath = "${{ github.workspace }}\repo"

        Register-PSResourceRepository -Name "LocalRepo" -URL $LocalRepoPath

        Publish-PSResource -Path $FullPath -Repository "LocalRepo"

        $NupkgPath = Get-ChildItem -Path $LocalRepoPath -Include "*.nupkg" -Recurse

        dotnet tool install --global gpr

        gpr push -k ${{ inputs.github-token }} $NupkgPath -r $NuGetUri
      shell: pwsh
