name: Publish PowerShell
description: |
  Publish a PowerShell module or script to GitHub Packages, the Posh Test
  Gallery, or the PowerShell Gallery.
inputs:
  token:
    description: |
      Token to authenticate.
    required: true
  target:
    description: |
      Set to `packages` for GitHub Packages, `testgallery` for PoshTest 
      Gallery, or `gallery` for PowerShell Gallery.
    required: true
  path:
    description: |
      Path to publish relative to the root of the project. Can either 
      be a .psd1 file, a .ps1 file, or a directory. If a directory, the action 
      will search for a .psd1 file in the root. If none are found, it will then 
      search for a .ps1 file in the root.
    required: true
runs:
  using: composite
  steps:
    - name: Validate Inputs
      run: . "$env:GITHUB_ACTION_PATH\src\steps\1_validate.ps1"
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_TARGET: ${{ inputs.target }}
        INPUT_PATH: ${{ inputs.path }}
      shell: pwsh
    - name: Prepare to Publish
      run: . "$env:GITHUB_ACTION_PATH\src\steps\2_prepare.ps1"
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_TARGET: ${{ inputs.target }}
        INPUT_PATH: ${{ inputs.path }}
      shell: pwsh
    - name: Publish to GitHub Packages
      run: . "$env:GITHUB_ACTION_PATH\src\steps\3_publish_to_packages.ps1"
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_TARGET: ${{ inputs.target }}
        INPUT_PATH: ${{ inputs.path }}
      shell: pwsh
    - name: Publish to Posh Test Gallery
      run: . "$env:GITHUB_ACTION_PATH\src\steps\4_publish_to_test_gallery.ps1"
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_TARGET: ${{ inputs.target }}
        INPUT_PATH: ${{ inputs.path }}
      shell: pwsh
    - name: Publish to PowerShell Gallery
      run: . "$env:GITHUB_ACTION_PATH\src\steps\5_publish_to_gallery.ps1"
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_TARGET: ${{ inputs.target }}
        INPUT_PATH: ${{ inputs.path }}
      shell: pwsh