name: Publish PowerShell to GitHub Packages
description: Publish a PowerShell module or script to GitHub Packages.
inputs:
  github-token:
    description: |
      Token to authenticate to GitHub.
    required: true
  publish-type:
    description: |
      Set to "module" to publish a module or "script" to publish a script.
    required: true
  path:
    description: |
      Path to publish relative to the root of the project. For a module, 
      should be a directory containing the .psm1 file in the root. For a script, 
      should be the path to the .ps1 file.
runs:
  using: "composite"
  steps:
    - name: Publish to Packages
      run: |
        Install-Module PowerShellGet -AllowPrerelease -Force -Repository PSGallery -SkipPublisherCheck

        $FullPath = "${{ github.workspace }}\${{ inputs.path }}"

        $NuGetUri = "https://nuget.pkg.github.com/${{ github.repository_owner }}"

        $LocalRepoPath = "${{ github.workspace }}\repo"

        Register-PSResourceRepository -Name "LocalRepo" -URL $LocalRepoPath

        Publish-PSResource -Path $FullPath -Repository "LocalRepo"

        $NupkgPath = Get-ChildItem -Path $LocalRepoPath -Include "*.nupkg" -Recurse

        dotnet tool install --global gpr

        gpr push -k ${{ inputs.github-token }} $NupkgPath -r $NuGetUri
      shell: pwsh
