name: CI
on:
  push:
    branches:
      - main
      - bugfix/**
      - feature/**
  workflow_dispatch:
env:
  JF_URL: https://natescherer.jfrog.io
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: pwsh
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Set Variables
        run: |
          "BARE_REPOSITORY=$($env:GITHUB_REPOSITORY.split("/")[1])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
          "RUNNER_OS_LOWER=$($env:RUNNER_OS.ToLower())" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
          "VERSION_SUFFIX=$(Get-Date -UFormat %s -Millisecond 0)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Metadata
        uses: natescherer/update-powershell-metadata-action@main
        with:
          path: test/library/TestModule-${{ env.RUNNER_OS_LOWER}}/TestModule-${{ env.RUNNER_OS_LOWER}}.psd1
          version: 1.0.1-alpha${{ env.VERSION_SUFFIX }}
      - name: Publish to Packages
        id: packages
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: packages
          path: test/library/TestModule-${{ env.RUNNER_OS_LOWER }}
      - name: Publish to NuGet
        id: nuget
        uses: ./
        with:
          token: ${{ secrets.JF_USER }}:${{ secrets.JF_ACCESS_TOKEN }}
          target: nuget
          path: test/library/TestModule-${{ env.RUNNER_OS_LOWER }}
          nugetUrl: ${{ env.JF_URL }}/artifactory/api/nuget/nuget
      - name: Run Pester Tests
        id: pester
        uses: zyborg/pester-tests-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_name: TestResults_${{ runner.os }}
          tests_fail_step: true
          gist_name: ${{ env.BARE_REPOSITORY }}_TestResults_${{ runner.os }}.md
          gist_badge_label: ${{ runner.os }}
          gist_token: ${{ secrets.PESTER_GIST_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}