name: CI
on:
  push:
    branches:
      - main
      - bugfix/**
      - feature/**
  workflow_dispatch:
env:
  JF_URL: https://natescherer.jfrog.io
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: pwsh
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Set Variables
        run: |
          "BARE_REPOSITORY=$($env:GITHUB_REPOSITORY.split("/")[1])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_USER: ${{ secrets.JF_USER }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - name: Create Artifactory Repo
        run: |
          $JsonPath = Join-Path $env:GITHUB_WORKSPACE test library artifactory_repo_$($env:RUNNER_OS.ToLower()).json
          jf rt repo-create $JsonPath
      # - name: Publish to Packages
      #   id: packages
      #   uses: ./
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     target: packages
      #     path: test
      - name: Publish to NuGet
        id: nuget
        uses: ./
        with:
          token: ${{ secrets.JF_USER }}:${{ secrets.JF_ACCESS_TOKEN }}
          target: nuget
          path: ${{ join(["test/library/testmodule-", env.RUNNER_OS], '') }}
          nugetUrl: ${{ env.JF_URL }}
      # - name: Run Pester Tests
      #   id: pester
      #   uses: zyborg/pester-tests-report@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     report_name: TestResults_${{ runner.os }}
      #     tests_fail_step: true
      #     gist_name: ${{ env.BARE_REPOSITORY }}_TestResults_${{ runner.os }}.md
      #     gist_badge_label: ${{ runner.os }}
      #     gist_token: ${{ secrets.PESTER_GIST_TOKEN }}